// Melengkapi kunci halaman baru yang belum ada pada berkas terjemahan Indonesia lama.
export default {
  checkin: {
    title: 'Check-in Harian', subtitle: 'Streak {{streak}} hari · {{monthDays}} hari bulan ini', rewardIntro: 'Check-in untuk mendapat putaran Roda Keberuntungan gratis 🎡 — streak lebih panjang memberi hadiah lebih besar', dayLabel: 'H{{day}}', peak: 'Puncak', daysUnit: 'h',
    tier: { starter: 'Dasar', premium: 'Premium', elite: 'Elite' },
    enhancedHint: 'Deposit atau pasang taruhan hari ini untuk membuka hadiah tambahan', enhancedUnlocked: 'Hadiah tambahan hari ini sudah terbuka', milestoneTitle: 'Pencapaian Bulanan', milestoneSubtitle: 'Streak lebih panjang, hadiah lebih besar!', yourSpins: 'Putaran Anda', thisWeek: 'Minggu Ini', claimShort: 'Klaim', streakResetHint: 'Streak akan direset jika Anda melewatkan satu hari.', daysWord: 'Hari', ctaCheckin: 'Check-in & Dapatkan Putaran', comeBackTomorrow: 'Kembali besok untuk putaran berikutnya!', claim: 'Check-in untuk putaran gratis', claimEnhanced: 'Klaim hadiah tambahan', claimed: 'Sudah check-in hari ini', claiming: 'Sedang check-in…', gotSpins: 'Anda mendapat {{n}} putaran!', goSpin: 'Ke Roda Keberuntungan →', spinEntry: 'Ada {{n}} putaran siap digunakan', entryTitle: 'Check-in Harian', entryTag: 'Harian', entryDesc: 'Check-in setiap hari untuk mendapat putaran gratis', entryCta: 'Check-in', cardReward: 'GRATIS', cardRewardLabel: 'Putaran Harian', cardBadge: 'Tanpa Deposit', cardStep1: 'Buka Bonus dan tekan Check-in setiap hari', cardStep2: 'Dapatkan putaran gratis — streak lebih panjang membuka hadiah lebih besar', floatLabel: 'Check-in', disabled: 'Program check-in sedang tidak tersedia',
  },
  common: { retry: 'Coba Lagi' },
  cs: {
    quickMenuTitle: 'Pertanyaan umum',
    orders: { depositIntro: 'Berikut pesanan deposit terbaru Anda:', withdrawIntro: 'Berikut pesanan penarikan terbaru Anda:', empty: 'Tidak ada pesanan terkait.', orderId: 'Pesanan', channel: 'Kanal', createdAt: 'Dibuat', creditedAt: 'Dikreditkan', completedAt: 'Selesai', rejectReason: 'Alasan', footerHelp: 'Masih ada pertanyaan? Ketik masalah Anda atau buka menu untuk menghubungi agen.', deposit_success: 'Dikreditkan', deposit_pending: 'Diproses', deposit_failed: 'Gagal', withdraw_success: 'Selesai', withdraw_pending: 'Diproses', withdraw_failed: 'Gagal' },
    quick: { deposit: 'Deposit belum masuk', withdrawal: 'Status penarikan', cannotWithdraw: 'Mengapa tidak bisa menarik?', kyc: 'Verifikasi KYC', promotions: 'Bonus & promosi', games: 'Masalah game', account: 'Akun & login', human: 'Hubungi agen manusia' },
  },
  kyc: {
    title: 'Verifikasi Identitas', subtitle: 'Wajib diselesaikan sebelum penarikan pertama.', settingEntry: 'Pengaturan KYC', settingTitle: 'Pengaturan KYC', settingSubtitle: 'Selesaikan verifikasi identitas untuk membuka penarikan.', stepPhone: 'Verifikasi telepon', stepDocument: 'Verifikasi identitas', stepFace: 'Pencocokan wajah', sendCode: 'Kirim kode', phoneLocked: 'Verifikasi hanya dapat menggunakan nomor telepon yang terdaftar.', bindPhoneCta: 'Tautkan nomor telepon', resendIn: 'Kirim ulang dalam {{s}} dtk', codeLabel: 'Kode verifikasi', verify: 'Verifikasi', fullName: 'Nama lengkap (sesuai identitas)', uploadId: 'Unggah foto identitas', submit: 'Kirim untuk verifikasi', capture: 'Ambil Foto', retake: 'Ambil Ulang', approved: 'Verifikasi disetujui!', rejected: 'Verifikasi gagal, silakan coba lagi', fillAll: 'Lengkapi semua kolom', close: 'Selesai', required: 'Verifikasi identitas untuk menarik dana', livenessNeutral: 'Tatap lurus ke kamera', livenessBlink: 'Kedipkan mata', livenessMouth: 'Buka mulut', cameraDenied: 'Akses kamera ditolak. Izinkan kamera di browser Anda.',
  },
  home: { highRebate: 'GAME CASHBACK TINGGI', recentPlayed: 'TERAKHIR DIMAINKAN', newGames: 'GAME BARU', casinoZone: 'LIVE CASINO', peryaZone: 'GAME PERYA', lotteryZone: 'LOTRE & LAINNYA', recommended: 'REKOMENDASI', baccaratZone: 'BACCARAT', highRtp: 'RTP TINGGI 97%+', sportsZone: 'GAME OLAHRAGA', providerZone: 'PROVIDER TERATAS', sportsEntry: 'SPORTSBOOK', sportsEntrySub: 'Taruhan NBA, PBA, tinju & lainnya', chipCasino: 'Kasino', chipPerya: 'Perya', chipLottery: 'Lotre' },
  spin: { checkinTab: 'CHECK-IN' },
  tasks: {
    pageTitle: 'Pusat Tugas', entrySub: 'Selesaikan tugas, dapatkan hadiah', empty: 'Belum ada tugas tersedia',
    group: { newbie: 'Tugas Pemula', daily: 'Tugas Harian', achievement: 'Pencapaian', social: 'Ikuti Kami' },
    path: { newbie: 'Pemain Baru', daily: 'Harian', growth: 'Pertumbuhan', social: 'Sosial' },
    pathSub: { newbie: 'Selesaikan pengaturan dan buka hadiah pertama', daily: 'Bangun rutinitas harian dan kumpulkan hadiah berulang', growth: 'Dapatkan nilai pertumbuhan dan cek progres VIP', social: 'Ikuti Telegram, Facebook, dan Viber resmi kami' },
    tree: { todayPath: 'Jalur Hari Ini', claimable: 'Dapat Diklaim', rewards: 'Hadiah', milestone: 'Pencapaian', vipTitle: 'Klub VIP', vipSub: 'Lihat level, manfaat, progres, dan riwayat hadiah VIP', vipBtn: 'Lihat VIP' },
    ball: { label: 'Tugas', short: 'Tugas', close: 'Tutup tombol tugas' },
    bar: { doingTag: 'Sedang berjalan', nextTag: 'Berikutnya', readyTag: 'Siap', backToTasks: 'Tugas', claimNow: 'Klaim', claimed: 'Masuk: {{reward}}', completed: 'Tugas selesai', close: 'Tutup bilah tugas', turnover: 'Syarat turnover {{n}}x' },
    claim: 'Klaim', claiming: 'Mengklaim…', claimed: 'Diklaim', done: 'Selesai', todo: 'Kerjakan', go: 'Buka', verify: 'Verifikasi', bind: 'Tautkan', submit: 'Kirim', rewardSpin: '+{{n}} putaran', rewardGrowth: '+{{n}} pertumbuhan', claimSuccess: 'Hadiah diterima: {{reward}}', claimFailed: 'Klaim gagal', codePlaceholder: 'Masukkan kode', codeSheetHint: 'Temukan kode di posting komunitas kami, lalu masukkan di bawah untuk mengklaim.', codeSheetGo: 'Lihat posting & ambil kode',
    codeSheet: { follow_viber: { step1: 'Tekan tombol di bawah untuk bergabung dengan komunitas Viber resmi', step2: 'Temukan kode pada pesan yang disematkan di atas', step3: 'Kembali dan masukkan kode untuk mengklaim hadiah', go: 'Gabung komunitas & ambil kode' }, follow_facebook: { step1: 'Tekan tombol di bawah untuk membuka dan mengikuti Facebook kami', step2: 'Temukan kode pada posting yang disematkan', step3: 'Kembali dan masukkan kode untuk mengklaim hadiah' } },
    visitThenClaim: 'Sudah dibuka — kembali dan tekan lagi untuk mengklaim', codeRequired: 'Masukkan kode', badCode: 'Kode salah, silakan periksa', notMember: 'Anda belum bergabung', submittedReview: 'Terkirim, menunggu pemeriksaan', screenshotPrompt: 'Tempel URL tangkapan layar',
    item: {
      daily_deposit_tier: { title: 'Deposit {{n}}+ Hari Ini', subtitle: 'Tingkat {{i}}/3 · direset harian' }, daily_bets: { title: 'Pasang {{n}} Taruhan Hari Ini', subtitle: 'Taruhan valid · direset harian', subtitleWithMin: 'Min. {{amount}} per taruhan · direset harian' }, daily_play: { title: 'Mainkan Game Pilihan Hari Ini', subtitle: 'Mainkan satu putaran di kategori pilihan' }, profile_complete: { title: 'Tautkan Akun Anda', subtitle: 'Tautkan Google & Telegram ke akun Anda' }, first_game: { title: 'Taruhan Pertama', subtitle: 'Mainkan game apa saja dan pasang taruhan' }, invite_milestone: { title: 'Undang Teman', subtitle: 'Undang teman mendaftar untuk mengklaim' }, agg_trial: { title: 'Klaim Bonus Pemula', subtitle: 'Klaim sekali tekan — tanpa deposit' }, agg_appdl: { title: 'Bonus Unduh Aplikasi', subtitle: 'Hadiah sekali untuk memasang App / PWA' }, agg_firstdep: { title: 'Deposit Pertama', subtitle: 'Dapatkan bonus pada deposit pertama' }, agg_birthday: { title: 'Buka Hadiah Ulang Tahun', subtitle: 'Verifikasi identitas untuk menyelaraskan tanggal lahir' }, agg_checkin: { title: 'Check-in Harian', subtitle: 'Check-in untuk mendapat kesempatan putar' }, checkin_ms: { title: 'Check-in {{n}} hari bulan ini', subtitle: 'Capai target untuk hadiah tambahan' },
    },
    earn: { rebate: 'Rebate dapat diklaim', vipLabel: 'Progres VIP', vipNext: '{{amt}} menuju VIP{{n}}', vipMax: 'Level tertinggi tercapai' },
    footer: { howTitle: 'Cara Kerja', step1Title: 'Selesaikan Tugas', step1Sub: 'Selesaikan tugas pemain baru, harian, dan sosial', step2Title: 'Klaim Hadiah', step2Sub: 'Terima bonus tunai atau putaran gratis', step3Title: 'Main & Tarik', step3Sub: 'Penuhi syarat turnover, lalu tarik dana', notesTitle: 'Aturan Hadiah', note1: 'Hadiah tunai memiliki syarat turnover sebelum penarikan.', note2: 'Tugas harian direset setiap hari pukul 00.00 (UTC+7 untuk IDR).', note3: 'Satu akun per pemain — akun duplikat tidak berhak mendapat hadiah.', note4: 'BETOGO berhak atas interpretasi akhir seluruh hadiah tugas.' },
  },
  lossRebate: {
    title: 'REBATE KERUGIAN', pageTitle: 'Rebate Kerugian Harian', subtitle: 'Dapatkan kembali {{rate}}% kerugian bersih — setiap hari', introTitle: 'Apa itu Rebate Kerugian?', introBody: 'Menang atau kalah, kami tetap mendukung Anda. Setiap hari kerugian bersih dari game yang memenuhi syarat dihitung dan {{rate}}% dikembalikan sebagai bonus — untuk semua level VIP, tanpa batas atas.', howTitle: 'Cara kerja', how1: 'Kerugian bersih = total taruhan dikurangi total kemenangan pada game yang memenuhi syarat hari itu.', how2: 'Rebate = kerugian bersih × {{rate}}%, tanpa batas.', how3: 'Dihitung otomatis sekali sehari untuk hari sebelumnya.', gamesTitle: 'Game yang memenuhi syarat', gamesBody: 'Slot dan Fishing memenuhi syarat. Live Casino dan taruhan olahraga tidak termasuk.', condTitle: 'Ketentuan', cond1: 'Total deposit minimal {{min}} dalam {{days}} hari terakhir (tidak wajib deposit hari ini).', cond2: 'Dasar rebate dibatasi sebesar deposit Anda pada hari tersebut.', claimTitle: 'Cara klaim', claimBody: 'Rebate harian tampil sebagai hadiah yang dapat diklaim di Pusat VIP — tekan untuk memasukkannya ke saldo.', claimCta: 'Ke Pusat VIP', claimNow: 'Klaim {{amt}}', noClaim: 'Belum ada yang dapat diklaim', viewHistory: 'Lihat riwayat klaim',
    status: { title: 'Rebate Anda (hari ini)', netLoss: 'Kerugian bersih hari ini', pendingLabel: 'Rebate siap diklaim', potential: 'Estimasi rebate ({{rate}}%)', needDeposit: 'Deposit ≥ {{min}} dalam {{days}} hari untuk membuka (sekarang {{dep}})', eligible: 'Memenuhi syarat — dapat diklaim di Pusat VIP setelah penyelesaian', pending: '{{amt}} sudah masuk dan siap diklaim', noLoss: 'Belum ada kerugian bersih hari ini — estimasi akan tampil secara real time.', remaining: 'Estimasi rebate menunggu penyelesaian', claimedToday: 'Diklaim hari ini', pendingSettle: 'Rebate hari ini belum diselesaikan; akan dapat diklaim setelah penyelesaian berikutnya. Lihat catatan untuk klaim sebelumnya.', settledAll: 'Rebate hari ini sudah selesai — periksa catatan Anda.' },
    disclaimer: 'Bonus tunduk pada syarat dan ketentuan. Operator berhak atas interpretasi akhir.', cardTag: 'REBATE HARIAN', cardTitle: 'Rebate Kerugian {{rate}}%', cardTagline: 'Dapatkan kembali {{rate}}% kerugian bersih setiap hari', cardCta: 'Pelajari', cardRewardLabel: 'Kerugian Kembali', cardBadge: 'Tanpa Batas',
  },
  vipPage: { tabs: { lossrebate: 'Rebate Kerugian' } },
  bonuses: {
    newPlayer: { title: 'Pemain Baru', freeGifts: 'Hadiah Gratis', howItWorks: 'Cara Kerja', trialTitle: 'Daftar sekarang dan dapatkan Rp{{amount}}!', trialDesc: 'Pemain baru mendapat bonus gratis setelah mendaftar — tanpa deposit.', appdlTitle: 'Unduh aplikasi dan dapatkan Rp{{amount}}!', appdlDesc: 'Pasang BETOGO di layar utama, buka aplikasi, lalu klaim.', firstdepTitle: 'Deposit pertama — bonus kejutan hingga Rp{{amount}}!', firstdepDesc: 'Bonus disiapkan khusus untuk Anda. Buka halaman deposit untuk melihat jumlah eksklusif.', cashbackCapped: 'Cashback tanpa batas — hingga Rp{{amount}} per bulan!', cashbackUnlimited: 'Cashback {{rate}}% tanpa batas untuk setiap taruhan!', cashbackDesc: 'Setiap taruhan mendapat cashback, menang atau kalah. Naik level untuk rate lebih tinggi.', ctaSignUp: 'Daftar Sekarang', ctaClaim: 'Klaim Rp{{amount}}', ctaInstall: 'Pasang Aplikasi', ctaReveal: 'Lihat Bonus Saya', ctaCashback: 'Lihat Cashback', done: 'Diklaim', footnote: 'Semua hadiah tunduk pada ketentuan BETOGO dan syarat turnover. Lihat setiap program di Bonus.', entryTitle: 'Hadiah Pemain Baru', entrySub: 'Hadiah sambutan hingga {{amount}}' },
    promos: { appdl: { tag: 'KHUSUS APLIKASI', title: 'Bonus Instal Aplikasi', tagline: 'Pasang & Klaim Rp{{amount}} Gratis', rewardLabel: 'Bonus Gratis', desc: 'Pasang aplikasi BETOGO atau tambahkan ke layar utama, lalu buka dan klaim Rp{{amount}} gratis — khusus pengguna aplikasi!', badge: 'Khusus App', cta: 'Pasang Sekarang', ctaClaim: 'Klaim Rp{{amount}}', ctaClaimed: 'Diklaim', claiming: 'Mengklaim...', claimSuccess: 'Rp{{amount}} masuk ke dompet Anda!', openInApp: 'Buka aplikasi yang sudah dipasang untuk mengklaim bonus', step1: 'Pasang aplikasi / Tambahkan ke Layar Utama', step2: 'Buka aplikasi dan klaim Rp{{amount}}' } },
  },
  wallet: { matrixPhpDeduct: 'PHP yang dipotong dari saldo' },
  games: { catAll: 'Semua', catHighRebate: 'Cashback Tinggi', catHighRtp: 'RTP Tinggi 97%+', peryaCarnival: 'Karnaval Perya', peryaCarnivalSub: 'Game klasik, jackpot & pesta', enter: 'Masuk' },
  referralPromo: { questBadge: 'Misi Hadiah', questMapTitle: 'Peta Misi 3 Circle', questRewardTag: 'Taruhan valid → hadiah', mapC1Title: 'Langsung', mapC1Desc: 'Teman yang memakai tautan Anda', mapC2Title: 'Dibagikan', mapC2Desc: 'Teman yang diundang C1', mapC3Title: 'Diperluas', mapC3Desc: 'Teman yang diundang C2', questShareTitle: 'Bagikan tautan resmi', questShareDesc: 'Tautan memastikan setiap anggota circle tercatat dengan benar.', questCircleTitle: 'Kembangkan 3 circle', questCircleDesc: 'C1, C2, dan C3 menunjukkan perkembangan jalur undangan.', questRewardTitle: 'Dapatkan sesuai rate', questRewardDesc: 'Taruhan yang memenuhi syarat diselesaikan sesuai rate circle ke dompet hadiah.' },
  pwa: {
    barTitle: 'Unduh Aplikasi Kami', barDesc: 'Menangkan Hadiah Besar!', barPromo: 'Dapatkan Bonus Gratis Rp{{amount}}!', barInstall: 'Pasang', downloadEntry: 'Unduh Aplikasi', tagline: 'Kasino · Slot · Bingo · Olahraga',
    guide: { title: 'Tambahkan ke Layar Utama', iosStep1: 'Tekan ikon “Bagikan”', iosStep2: 'Tekan “Tambahkan ke Layar Utama”', andStep1: 'Tekan ikon “Menu”', andStep2: 'Tekan “Tambahkan ke layar utama”', step3: 'Tekan “Tambahkan”', addBookmark: 'Tambah Bookmark', addFavorites: 'Tambah ke Favorit', findOnPage: 'Cari di Halaman', addToHome: 'Tambah ke Layar Utama', bookmarks: 'Bookmark', downloads: 'Unduhan', recentTabs: 'Tab terbaru', cancel: 'Batal', add: 'Tambahkan' },
  },
}
