// 568Win 厂商名归一化：上游 provider 原始值 -> 统一显示名 + 简称
// 源头是 data/provider-alias.json (canonical_meta)，改映射后用 scripts/gen_canon 重新生成
// 由 scratchpad gen_canon.py 生成，勿手改

const RAW_TO_CANON: Record<string, { display: string; short: string }> = {
  '168game': { display: '168 Game', short: '168' },
  '1x2 gaming': { display: '1x2 Gaming', short: '1X2' },
  '568wingames': { display: '568WinGames', short: '568W' },
  '5ggames': { display: '5G Games', short: '5G' },
  '77 gaming': { display: '77 Gaming', short: '77G' },
  '7mojos casino': { display: '7Mojos', short: '7MJ' },
  '93connect': { display: '93Connect', short: '93C' },
  'abracadabra': { display: 'AbraCadabra', short: 'ABRA' },
  'advantplay': { display: 'AdvantPlay', short: 'ADP' },
  'afb sports': { display: 'AFB Sports', short: 'AFBS' },
  'afbgaming': { display: 'AFB Gaming', short: 'AFB' },
  'africanbuffalo': { display: 'African Buffalo', short: 'AFB2' },
  'allbet': { display: 'AllBet', short: 'AB' },
  'apgaming': { display: 'AP Gaming', short: 'APG' },
  'apollo': { display: 'Apollo', short: 'APO' },
  'avatarux': { display: 'AvatarUX', short: 'AUX' },
  'aviatrix': { display: 'Aviatrix', short: 'AVX' },
  'biggaming': { display: 'Big Gaming', short: 'BGM' },
  'bigpot gaming': { display: 'Bigpot Gaming', short: 'BIGPOT' },
  'bigtimegaming': { display: 'Big Time Gaming', short: 'BTG' },
  'blueprint': { display: 'Blueprint', short: 'BP' },
  'bng': { display: 'BNG', short: 'BNG' },
  'bolegaming': { display: 'Bole Gaming', short: 'BOLE' },
  'booongo': { display: 'BNG', short: 'BNG' },
  'btisports': { display: 'BTi Sports', short: 'BTI' },
  'bullshark': { display: 'Bullshark', short: 'BSK' },
  'cc88': { display: 'CC88', short: 'CC88' },
  'clawbuster': { display: 'Clawbuster', short: 'CLB' },
  'clotplay': { display: 'ClotPlay', short: 'CLOT' },
  'cq9': { display: 'CQ9', short: 'CQ9' },
  'cq9 casino': { display: 'CQ9', short: 'CQ9' },
  'ct interactive': { display: 'CT Interactive', short: 'CTI' },
  'dragoon soft': { display: 'Dragoon Soft', short: 'DS' },
  'dragoonsoft': { display: 'Dragoon Soft', short: 'DS' },
  'dreamgaming': { display: 'Dream Gaming', short: 'DG' },
  'endorphina': { display: 'Endorphina', short: 'EDP' },
  'evolutiongaming': { display: 'Evolution', short: 'EVO' },
  'evoplay': { display: 'Evoplay', short: 'EVP' },
  'expanse': { display: 'Expanse', short: 'EXP' },
  'ezugi': { display: 'Ezugi', short: 'EZG' },
  'fachai': { display: 'FaChai', short: 'FC' },
  'fantasma': { display: 'Fantasma', short: 'FTM' },
  'fastspin': { display: 'Fastspin', short: 'FS' },
  'fugaso': { display: 'Fugaso', short: 'FUG' },
  'funkygames': { display: 'Funky Games', short: 'FG' },
  'gameart': { display: 'GameArt', short: 'GA' },
  'gameplaylivecasino': { display: 'GamePlay', short: 'GPI' },
  'gameplaylottery': { display: 'GamePlay', short: 'GPI' },
  'gameplayslot': { display: 'GamePlay', short: 'GPI' },
  'gaming corps': { display: 'Gaming Corps', short: 'GC' },
  'gamzix': { display: 'Gamzix', short: 'GZX' },
  'greendragon': { display: 'Green Dragon', short: 'GD' },
  'habanero': { display: 'Habanero', short: 'HBN' },
  'hacksaw': { display: 'Hacksaw Gaming', short: 'HS' },
  'hacksawgaming': { display: 'Hacksaw Gaming', short: 'HS' },
  'idnlive': { display: 'IDN', short: 'IDN' },
  'idnslot': { display: 'IDN', short: 'IDN' },
  'indialotto': { display: 'India Lotto', short: 'INL' },
  'ionlc': { display: 'ION Casino', short: 'ION' },
  'iron dog studio': { display: 'Iron Dog Studio', short: 'IDS' },
  'jdb': { display: 'JDB', short: 'JDB' },
  'jili': { display: 'JILI', short: 'JILI' },
  'jiligaming': { display: 'JILI', short: 'JILI' },
  'jokergaming': { display: 'Joker Gaming', short: 'JOKER' },
  'ka gaming': { display: 'KA Gaming', short: 'KA' },
  'kagaming': { display: 'KA Gaming', short: 'KA' },
  'kalamba': { display: 'Kalamba', short: 'KAL' },
  'king midas': { display: 'King Midas', short: 'KM' },
  'kingmidas': { display: 'King Midas', short: 'KM' },
  'kissgaming': { display: 'Kiss Gaming', short: 'KISS' },
  'lambdagaming': { display: 'Lambda Gaming', short: 'LBD' },
  'live22': { display: 'Live22', short: 'L22' },
  'luckymonaco': { display: 'Lucky Monaco', short: 'LKM' },
  'luckysports': { display: 'Lucky Sports', short: 'LKS' },
  'manna play': { display: 'Manna Play', short: 'MNP' },
  'mascot gaming': { display: 'Mascot Gaming', short: 'MAS' },
  'microgaming': { display: 'Microgaming', short: 'MG' },
  'mikiworld': { display: 'MikiWorld', short: 'MIKI' },
  'mikiworldlivecasino': { display: 'MikiWorld', short: 'MIKI' },
  'mobilots': { display: 'Mobilots', short: 'MBL' },
  'mpoker': { display: 'MPoker', short: 'MPK' },
  'mt': { display: 'MT', short: 'MT' },
  'naga games': { display: 'Naga Games', short: 'NAGA' },
  'nagagames': { display: 'Naga Games', short: 'NAGA' },
  'netent': { display: 'NetEnt', short: 'NE' },
  'netentextended': { display: 'NetEnt', short: 'NE' },
  'netgame': { display: 'NetGame', short: 'NG' },
  'nextspin': { display: 'Nextspin', short: 'NXS' },
  'nolimitcity': { display: 'Nolimit City', short: 'NLC' },
  'nownow gaming': { display: 'Nownow Gaming', short: 'NN' },
  'oglive': { display: 'OG Live', short: 'OG' },
  'onlyplay': { display: 'Onlyplay', short: 'OPL' },
  'pandasports': { display: 'Panda Sports', short: 'PDS' },
  'pegasusslot': { display: 'Pegasus', short: 'PEG' },
  'peter & sons': { display: 'Peter & Sons', short: 'PNS' },
  'pg soft': { display: 'PG Soft', short: 'PG' },
  'pgsoft': { display: 'PG Soft', short: 'PG' },
  'phoenix7': { display: 'Phoenix7', short: 'PH7' },
  'platipus gaming': { display: 'Platipus', short: 'PLA' },
  'play\'n go': { display: 'Play\'n GO', short: 'PNG' },
  'playace': { display: 'PlayAce', short: 'PACE' },
  'playstar': { display: 'PlayStar', short: 'PS' },
  'playtech': { display: 'Playtech', short: 'PT' },
  'playtech casino': { display: 'Playtech', short: 'PT' },
  'poggiplay': { display: 'PoggiPlay', short: 'POGGI' },
  'popiplay gaming': { display: 'Popiplay', short: 'POPI' },
  'pragmatic play casino': { display: 'Pragmatic Play', short: 'PP' },
  'pragmaticplay': { display: 'Pragmatic Play', short: 'PP' },
  'pragmaticplaycasino': { display: 'Pragmatic Play', short: 'PP' },
  'predix': { display: 'Predix', short: 'PDX' },
  'prospect gaming': { display: 'Prospect Gaming', short: 'PRO' },
  'qora': { display: 'Qora', short: 'QORA' },
  'quickspin': { display: 'Quickspin', short: 'QS' },
  'ready play': { display: 'Ready Play', short: 'RDY' },
  'red tiger': { display: 'Red Tiger', short: 'RT' },
  'redrake': { display: 'Red Rake', short: 'RR' },
  'reelplay': { display: 'ReelPlay', short: 'RPL' },
  'relaxgaming': { display: 'Relax Gaming', short: 'RELAX' },
  'revdev': { display: 'RevDev', short: 'REV' },
  'revolver gaming': { display: 'Revolver Gaming', short: 'RVG' },
  'rich88': { display: 'Rich88', short: 'R88' },
  'rival powered': { display: 'Rival Powered', short: 'RIV' },
  'rogue': { display: 'Rogue', short: 'ROG' },
  'royalslotgaming': { display: 'Royal Slot Gaming', short: 'RSG' },
  'rtg slots': { display: 'RTG Slots', short: 'RTG' },
  'rubyplay': { display: 'RubyPlay', short: 'RUBY' },
  'saba sports': { display: 'Saba Sports', short: 'SABA' },
  'sagaming': { display: 'SA Gaming', short: 'SA' },
  'sboslot': { display: 'SBO Slot', short: 'SBO' },
  'sexygaming': { display: 'Sexy Gaming', short: 'SEXY' },
  'skywind casino': { display: 'Skywind', short: 'SW' },
  'speedy tomatoes': { display: 'Speedy Tomatoes', short: 'SPT' },
  'splus': { display: 'SPlus', short: 'SPL' },
  'spribe': { display: 'Spribe', short: 'SPRIBE' },
  'tcgaming': { display: 'TC Gaming', short: 'TCG' },
  'thunderkick': { display: 'Thunderkick', short: 'TK' },
  'tomhorn': { display: 'Tom Horn', short: 'TH' },
  'triple pg': { display: 'Triple PG', short: 'TPG' },
  'turbo games': { display: 'Turbo Games', short: 'TURBO' },
  'upgames': { display: 'Upgames', short: 'UPG' },
  'vagaming': { display: 'VA Gaming', short: 'VA' },
  'vgaming': { display: 'VGaming', short: 'VG' },
  'viacasino': { display: 'Via Casino', short: 'VIA' },
  'voltent': { display: 'VoltEnt', short: 'VOLT' },
  'wanmei': { display: 'WanMei', short: 'WME' },
  'wcasino': { display: 'WCasino', short: 'WCA' },
  'worldmatch': { display: 'WorldMatch', short: 'WM' },
  'ws168cockfighting': { display: 'WS168', short: 'WS168' },
  'yeebet': { display: 'YeeBet', short: 'YEE' },
  'yggdrasil': { display: 'Yggdrasil', short: 'YGG' },
  'ygr': { display: 'YGR', short: 'YGR' },
}

export function normalizeWin568Provider(raw: string | null): { provider: string | null; short: string | null } {
  if (!raw) return { provider: null, short: null }
  const hit = RAW_TO_CANON[raw.trim().toLowerCase()]
  return hit ? { provider: hit.display, short: hit.short } : { provider: raw, short: null }
}
