/** 游戏商全称 → 行业通用简称（2-4 字母） */
const SHORT_NAMES: Record<string, string> = {
  'Apparat':        'APP',
  'Belatra Games':  'BEL',
  'BGaming':        'BG',
  'Caleta':         'CAL',
  'Clawbuster':     'CLW',
  'CTInteractive':  'CTi',
  'Endorphina':     'END',
  'Evoplay':        'EVO',
  'FormulaSpin':    'FSP',
  'FunkyGames':     'FUN',
  'Hacksawgaming':  'HSW',
  'Igrosoft':       'IGS',
  'JDB':            'JDB',
  'JiliGames':      'JILI',
  'KAGaming':       'KA',
  'Kalamba':        'KLB',
  'No Limit City':  'NLC',
  'PeterAndSons':   'P&S',
  'Platipus':       'PLT',
  'PlayHub':        'PHB',
  'PlayNGo':        'PNG',
  'PragmaticPlay':  'PP',
  'Relax Gaming':   'RLX',
  'Rich88':         'R88',
  'Rollback Test':  'TEST',
  'Slotopia':       'STP',
  'SmartSoft':      'SMS',
  'Spribe':         'SPB',
  'Thunderkick':    'TK',
  'Vivogaming':     'VIVO',
  // 以下为 568Win 统一后的显示名(迁移134,源头 data/provider-alias.json canonical_meta)
  '168 Game': '168',
  '1x2 Gaming': '1X2',
  '568WinGames': '568W',
  '5G Games': '5G',
  '77 Gaming': '77G',
  '7Mojos': '7MJ',
  '93Connect': '93C',
  'AbraCadabra': 'ABRA',
  'AdvantPlay': 'ADP',
  'AFB Gaming': 'AFB',
  'AFB Sports': 'AFBS',
  'African Buffalo': 'AFB2',
  'AllBet': 'AB',
  'AP Gaming': 'APG',
  'Apollo': 'APO',
  'AvatarUX': 'AUX',
  'Aviatrix': 'AVX',
  'Big Gaming': 'BGM',
  'Bigpot Gaming': 'BIGPOT',
  'Big Time Gaming': 'BTG',
  'Blueprint': 'BP',
  'Bole Gaming': 'BOLE',
  'BTi Sports': 'BTI',
  'Bullshark': 'BSK',
  'ClotPlay': 'CLOT',
  'CT Interactive': 'CTI',
  'Dragoon Soft': 'DS',
  'Dream Gaming': 'DG',
  'Evolution': 'EVO',
  'Expanse': 'EXP',
  'Ezugi': 'EZG',
  'FaChai': 'FC',
  'Fantasma': 'FTM',
  'Fastspin': 'FS',
  'Fugaso': 'FUG',
  'Funky Games': 'FG',
  'GameArt': 'GA',
  'GamePlay': 'GPI',
  'Gaming Corps': 'GC',
  'Gamzix': 'GZX',
  'Green Dragon': 'GD',
  'Habanero': 'HBN',
  'Hacksaw Gaming': 'HS',
  'India Lotto': 'INL',
  'ION Casino': 'ION',
  'Iron Dog Studio': 'IDS',
  'Joker Gaming': 'JOKER',
  'KA Gaming': 'KA',
  'King Midas': 'KM',
  'Kiss Gaming': 'KISS',
  'Lambda Gaming': 'LBD',
  'Live22': 'L22',
  'Lucky Monaco': 'LKM',
  'Lucky Sports': 'LKS',
  'Manna Play': 'MNP',
  'Mascot Gaming': 'MAS',
  'Microgaming': 'MG',
  'MikiWorld': 'MIKI',
  'Mobilots': 'MBL',
  'MPoker': 'MPK',
  'Naga Games': 'NAGA',
  'NetEnt': 'NE',
  'NetGame': 'NG',
  'Nextspin': 'NXS',
  'Nolimit City': 'NLC',
  'Nownow Gaming': 'NN',
  'OG Live': 'OG',
  'Onlyplay': 'OPL',
  'Panda Sports': 'PDS',
  'Pegasus': 'PEG',
  'Peter & Sons': 'PNS',
  'PG Soft': 'PG',
  'Phoenix7': 'PH7',
  'PlayAce': 'PACE',
  "Play'n GO": 'PNG',
  'PlayStar': 'PS',
  'Playtech': 'PT',
  'PoggiPlay': 'POGGI',
  'Popiplay': 'POPI',
  'Pragmatic Play': 'PP',
  'Predix': 'PDX',
  'Prospect Gaming': 'PRO',
  'Qora': 'QORA',
  'Quickspin': 'QS',
  'Ready Play': 'RDY',
  'Red Rake': 'RR',
  'Red Tiger': 'RT',
  'ReelPlay': 'RPL',
  'RevDev': 'REV',
  'Revolver Gaming': 'RVG',
  'Rival Powered': 'RIV',
  'Rogue': 'ROG',
  'Royal Slot Gaming': 'RSG',
  'RTG Slots': 'RTG',
  'RubyPlay': 'RUBY',
  'Saba Sports': 'SABA',
  'SA Gaming': 'SA',
  'SBO Slot': 'SBO',
  'Sexy Gaming': 'SEXY',
  'Skywind': 'SW',
  'Speedy Tomatoes': 'SPT',
  'SPlus': 'SPL',
  'TC Gaming': 'TCG',
  'Tom Horn': 'TH',
  'Triple PG': 'TPG',
  'Turbo Games': 'TURBO',
  'Upgames': 'UPG',
  'VA Gaming': 'VA',
  'VGaming': 'VG',
  'Via Casino': 'VIA',
  'VoltEnt': 'VOLT',
  'WanMei': 'WME',
  'WCasino': 'WCA',
  'WorldMatch': 'WM',
  'YeeBet': 'YEE',
  'Yggdrasil': 'YGG',
}

export function shortProviderName(provider: string): string {
  return SHORT_NAMES[provider] ?? provider
}
