#!/usr/bin/env bash
# BetoGo 本地一键部署：同步 .env、MySQL betogo、Nacos namespace/配置、Docker 重建
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

log() { printf '==> %s\n' "$*"; }

# ── 1. Merge missing keys from .env.example → .env ─────────────────
if [[ ! -f .env ]]; then
  log "Creating .env from .env.example"
  cp .env.example .env
fi

merge_env_key() {
  local key="$1"
  if grep -q "^${key}=" .env 2>/dev/null; then
    return 0
  fi
  local line
  line="$(grep "^${key}=" .env.example 2>/dev/null | head -1 || true)"
  if [[ -n "$line" ]]; then
    printf '%s\n' "$line" >> .env
    log "Added to .env: ${key}"
  fi
}

while IFS= read -r key; do
  [[ -z "$key" || "$key" =~ ^# ]] && continue
  merge_env_key "$key"
done < <(grep -E '^[A-Z][A-Z0-9_]*=' .env.example | cut -d= -f1)

# ── 2. Docker Compose up (infra first) ───────────────────────────────
log "Starting / updating Docker services"
docker compose up -d mysql redis rabbitmq nacos

log "Waiting for MySQL..."
for i in $(seq 1 30); do
  if docker exec tma-mysql mysqladmin ping -h localhost -uroot -p"${MYSQL_ROOT_PASSWORD:-root_dev_only}" --silent 2>/dev/null; then
    break
  fi
  sleep 2
done

# ── 3. MySQL: betogo database ──────────────────────────────────────
log "Ensuring MySQL database betogo"
docker exec tma-mysql mysql -uroot -p"${MYSQL_ROOT_PASSWORD:-root_dev_only}" -e \
  "CREATE DATABASE IF NOT EXISTS betogo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null \
  || docker exec tma-mysql mysql -uroot -proot_dev_only -e \
  "CREATE DATABASE IF NOT EXISTS betogo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

# ── 4. Nacos: namespace + bff-node config ──────────────────────────
log "Waiting for Nacos..."
for i in $(seq 1 40); do
  if curl -sf "http://127.0.0.1:${NACOS_PORT:-8848}/nacos/v1/console/health/readiness" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

NACOS_ADDR="http://127.0.0.1:${NACOS_PORT:-8848}"
NS="${NACOS_NAMESPACE:-batogo}"

log "Ensuring Nacos namespace: ${NS}"
curl -sf -X POST "${NACOS_ADDR}/nacos/v1/console/namespaces" \
  -d "customNamespaceId=${NS}&namespaceName=BetoGo&namespaceDesc=BetoGo%20local" \
  >/dev/null || true

# Load secrets from .env for Nacos seed (local only)
set -a
# shellcheck disable=SC1091
source .env
set +a

BFF_NACOS_CONTENT="$(cat <<EOF
# Auto-generated by scripts/local-deploy.sh — local dev
NODE_ENV=development
USDT_TO_PHP_RATE=${USDT_TO_PHP_RATE:-58}
TELEGRAM_BOT_USERNAME=${VITE_TELEGRAM_BOT_USERNAME:-BetoGoBot}
TELEGRAM_WEB_APP_URL=${VITE_TELEGRAM_WEB_APP_URL:-https://www.188facai.com}
AMMER_PAY_PROVIDER_TOKEN=${AMMER_PAY_PROVIDER_TOKEN:-}
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-https://www.188facai.com/auth/google/callback}
REDIS_URL=redis://redis:6379
MYSQL_HOST=mysql
MYSQL_PORT=3306
MYSQL_DATABASE=betogo
EOF
)"

log "Publishing Nacos config dataId=bff-node (namespace ${NS})"
curl -sf -X POST "${NACOS_ADDR}/nacos/v1/cs/configs" \
  --data-urlencode "dataId=bff-node" \
  --data-urlencode "group=DEFAULT_GROUP" \
  --data-urlencode "tenant=${NS}" \
  --data-urlencode "type=properties" \
  --data-urlencode "content=${BFF_NACOS_CONTENT}" \
  >/dev/null

# ── 5. Rebuild app images ────────────────────────────────────────────
log "Building and starting bff-node + web-tma"
docker compose up -d --build bff-node web-tma

log "Service status:"
docker compose ps

log "Health checks"
curl -sf "http://127.0.0.1:${BFF_PORT:-3000}/health" >/dev/null && log "  BFF /health: ok" || log "  BFF /health: FAIL"
curl -sf -o /dev/null "http://127.0.0.1:${WEB_TMA_PORT:-5173}/" && log "  web-tma :5173: ok" || log "  web-tma: FAIL"
curl -sf -o /dev/null "${NACOS_ADDR}/nacos/" && log "  Nacos :8848: ok" || log "  Nacos: FAIL"

log "Done. Client: http://localhost:${WEB_TMA_PORT:-5173}  BFF: http://localhost:${BFF_PORT:-3000}/api/v1"
