CREATE TABLE `bg_568win_game` (
  `game_id`               INT          NOT NULL COMMENT '568Win gameID',
  `game_provider_id`      INT          NOT NULL COMMENT '568Win gameProviderId/GpId',
  `provider`              VARCHAR(128) NULL,
  `new_game_type`         INT          NULL,
  `game_type`             INT          NULL,
  `rank_no`               INT          NULL,
  `device`                VARCHAR(16)  NULL,
  `platform`              VARCHAR(32)  NULL,
  `rtp`                   DECIMAL(8,2) NULL,
  `rows_count`            INT          NULL,
  `reels_count`           INT          NULL,
  `lines_count`           INT          NULL,
  `name_en`               VARCHAR(255) NULL,
  `name_zh`               VARCHAR(255) NULL,
  `icon_url`              VARCHAR(512) NULL,
  `supported_currencies`  JSON         NULL,
  `block_countries`       JSON         NULL,
  `is_enabled`            TINYINT(1)   NOT NULL DEFAULT 0,
  `is_maintain`           TINYINT(1)   NOT NULL DEFAULT 0,
  `provider_status`       VARCHAR(32)  NULL,
  `is_provider_online`    TINYINT(1)   NOT NULL DEFAULT 0,
  `is_provide_commission` TINYINT(1)   NOT NULL DEFAULT 0,
  `has_hedge_bet`         TINYINT(1)   NOT NULL DEFAULT 0,
  `raw_game`              JSON         NULL,
  `raw_response`          JSON         NULL,
  `synced_at`             DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at`            DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at`            DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`game_id`),
  KEY `idx_enabled_type` (`is_enabled`, `new_game_type`),
  KEY `idx_provider` (`provider`),
  KEY `idx_rank` (`rank_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='568Win 游戏列表缓存';
