-- 134: 厂商名统一 + 简称
-- provider 统一为规范显示名(如 Jili/JiLiGaming→JILI)，新增 provider_short 简称列
-- 映射源头 data/provider-alias.json canonical_meta；同步入库时 core-node 会做同样归一化
SET NAMES utf8mb4;

ALTER TABLE bg_568win_game
  ADD COLUMN provider_short VARCHAR(16) NULL COMMENT '厂商简称' AFTER provider,
  ADD KEY idx_provider_short (provider_short);

UPDATE bg_568win_game SET provider = '168 Game', provider_short = '168' WHERE provider IN ('168 Game', '168game');
UPDATE bg_568win_game SET provider = '1x2 Gaming', provider_short = '1X2' WHERE provider IN ('1x2 Gaming');
UPDATE bg_568win_game SET provider = '568WinGames', provider_short = '568W' WHERE provider IN ('568WinGames');
UPDATE bg_568win_game SET provider = '5G Games', provider_short = '5G' WHERE provider IN ('5G Games', '5GGames');
UPDATE bg_568win_game SET provider = '77 Gaming', provider_short = '77G' WHERE provider IN ('77 Gaming');
UPDATE bg_568win_game SET provider = '7Mojos', provider_short = '7MJ' WHERE provider IN ('7Mojos', '7Mojos Casino');
UPDATE bg_568win_game SET provider = '93Connect', provider_short = '93C' WHERE provider IN ('93Connect', '93connect');
UPDATE bg_568win_game SET provider = 'AbraCadabra', provider_short = 'ABRA' WHERE provider IN ('AbraCadabra');
UPDATE bg_568win_game SET provider = 'AdvantPlay', provider_short = 'ADP' WHERE provider IN ('AdvantPlay');
UPDATE bg_568win_game SET provider = 'AFB Gaming', provider_short = 'AFB' WHERE provider IN ('AFB Gaming', 'AFBGaming');
UPDATE bg_568win_game SET provider = 'AFB Sports', provider_short = 'AFBS' WHERE provider IN ('AFB Sports');
UPDATE bg_568win_game SET provider = 'African Buffalo', provider_short = 'AFB2' WHERE provider IN ('African Buffalo', 'AfricanBuffalo');
UPDATE bg_568win_game SET provider = 'AllBet', provider_short = 'AB' WHERE provider IN ('AllBet');
UPDATE bg_568win_game SET provider = 'AP Gaming', provider_short = 'APG' WHERE provider IN ('AP Gaming', 'APGaming');
UPDATE bg_568win_game SET provider = 'Apollo', provider_short = 'APO' WHERE provider IN ('Apollo');
UPDATE bg_568win_game SET provider = 'AvatarUX', provider_short = 'AUX' WHERE provider IN ('AvatarUX');
UPDATE bg_568win_game SET provider = 'Aviatrix', provider_short = 'AVX' WHERE provider IN ('Aviatrix');
UPDATE bg_568win_game SET provider = 'Big Gaming', provider_short = 'BGM' WHERE provider IN ('Big Gaming', 'BigGaming');
UPDATE bg_568win_game SET provider = 'Bigpot Gaming', provider_short = 'BIGPOT' WHERE provider IN ('Bigpot Gaming');
UPDATE bg_568win_game SET provider = 'Big Time Gaming', provider_short = 'BTG' WHERE provider IN ('Big Time Gaming', 'BigTimeGaming');
UPDATE bg_568win_game SET provider = 'Blueprint', provider_short = 'BP' WHERE provider IN ('Blueprint');
UPDATE bg_568win_game SET provider = 'Bole Gaming', provider_short = 'BOLE' WHERE provider IN ('Bole Gaming', 'BoleGaming');
UPDATE bg_568win_game SET provider = 'BNG', provider_short = 'BNG' WHERE provider IN ('BNG', 'Booongo');
UPDATE bg_568win_game SET provider = 'BTi Sports', provider_short = 'BTI' WHERE provider IN ('BTi Sports', 'BTiSports');
UPDATE bg_568win_game SET provider = 'Bullshark', provider_short = 'BSK' WHERE provider IN ('Bullshark');
UPDATE bg_568win_game SET provider = 'CC88', provider_short = 'CC88' WHERE provider IN ('CC88');
UPDATE bg_568win_game SET provider = 'Clawbuster', provider_short = 'CLB' WHERE provider IN ('Clawbuster');
UPDATE bg_568win_game SET provider = 'ClotPlay', provider_short = 'CLOT' WHERE provider IN ('ClotPlay', 'Clotplay');
UPDATE bg_568win_game SET provider = 'CQ9', provider_short = 'CQ9' WHERE provider IN ('CQ9', 'CQ9 Casino');
UPDATE bg_568win_game SET provider = 'CT Interactive', provider_short = 'CTI' WHERE provider IN ('CT Interactive');
UPDATE bg_568win_game SET provider = 'Dragoon Soft', provider_short = 'DS' WHERE provider IN ('Dragoon Soft', 'DragoonSoft');
UPDATE bg_568win_game SET provider = 'Dream Gaming', provider_short = 'DG' WHERE provider IN ('Dream Gaming', 'DreamGaming');
UPDATE bg_568win_game SET provider = 'Endorphina', provider_short = 'EDP' WHERE provider IN ('Endorphina');
UPDATE bg_568win_game SET provider = 'Evolution', provider_short = 'EVO' WHERE provider IN ('Evolution', 'EvolutionGaming');
UPDATE bg_568win_game SET provider = 'Evoplay', provider_short = 'EVP' WHERE provider IN ('Evoplay');
UPDATE bg_568win_game SET provider = 'Expanse', provider_short = 'EXP' WHERE provider IN ('Expanse');
UPDATE bg_568win_game SET provider = 'Ezugi', provider_short = 'EZG' WHERE provider IN ('Ezugi');
UPDATE bg_568win_game SET provider = 'FaChai', provider_short = 'FC' WHERE provider IN ('FaChai');
UPDATE bg_568win_game SET provider = 'Fantasma', provider_short = 'FTM' WHERE provider IN ('Fantasma');
UPDATE bg_568win_game SET provider = 'Fastspin', provider_short = 'FS' WHERE provider IN ('Fastspin');
UPDATE bg_568win_game SET provider = 'Fugaso', provider_short = 'FUG' WHERE provider IN ('Fugaso');
UPDATE bg_568win_game SET provider = 'Funky Games', provider_short = 'FG' WHERE provider IN ('Funky Games', 'FunkyGames');
UPDATE bg_568win_game SET provider = 'GameArt', provider_short = 'GA' WHERE provider IN ('GameArt');
UPDATE bg_568win_game SET provider = 'GamePlay', provider_short = 'GPI' WHERE provider IN ('GamePlay', 'GamePlayLiveCasino', 'GamePlayLottery', 'GamePlaySlot');
UPDATE bg_568win_game SET provider = 'Gaming Corps', provider_short = 'GC' WHERE provider IN ('Gaming Corps');
UPDATE bg_568win_game SET provider = 'Gamzix', provider_short = 'GZX' WHERE provider IN ('Gamzix');
UPDATE bg_568win_game SET provider = 'Green Dragon', provider_short = 'GD' WHERE provider IN ('Green Dragon', 'GreenDragon');
UPDATE bg_568win_game SET provider = 'Habanero', provider_short = 'HBN' WHERE provider IN ('Habanero');
UPDATE bg_568win_game SET provider = 'Hacksaw Gaming', provider_short = 'HS' WHERE provider IN ('Hacksaw', 'Hacksaw Gaming', 'HacksawGaming');
UPDATE bg_568win_game SET provider = 'IDN', provider_short = 'IDN' WHERE provider IN ('IDN', 'IDNLive', 'IDNSlot');
UPDATE bg_568win_game SET provider = 'India Lotto', provider_short = 'INL' WHERE provider IN ('India Lotto', 'IndiaLotto');
UPDATE bg_568win_game SET provider = 'ION Casino', provider_short = 'ION' WHERE provider IN ('ION Casino', 'IONLC');
UPDATE bg_568win_game SET provider = 'Iron Dog Studio', provider_short = 'IDS' WHERE provider IN ('Iron Dog Studio');
UPDATE bg_568win_game SET provider = 'JDB', provider_short = 'JDB' WHERE provider IN ('JDB');
UPDATE bg_568win_game SET provider = 'JILI', provider_short = 'JILI' WHERE provider IN ('JILI', 'JiLiGaming', 'Jili');
UPDATE bg_568win_game SET provider = 'Joker Gaming', provider_short = 'JOKER' WHERE provider IN ('Joker Gaming', 'JokerGaming');
UPDATE bg_568win_game SET provider = 'KA Gaming', provider_short = 'KA' WHERE provider IN ('KA Gaming', 'KAGaming');
UPDATE bg_568win_game SET provider = 'Kalamba', provider_short = 'KAL' WHERE provider IN ('Kalamba');
UPDATE bg_568win_game SET provider = 'King Midas', provider_short = 'KM' WHERE provider IN ('King Midas', 'KingMidas');
UPDATE bg_568win_game SET provider = 'Kiss Gaming', provider_short = 'KISS' WHERE provider IN ('Kiss Gaming', 'KissGaming');
UPDATE bg_568win_game SET provider = 'Lambda Gaming', provider_short = 'LBD' WHERE provider IN ('Lambda Gaming', 'LambdaGaming');
UPDATE bg_568win_game SET provider = 'Live22', provider_short = 'L22' WHERE provider IN ('Live22');
UPDATE bg_568win_game SET provider = 'Lucky Monaco', provider_short = 'LKM' WHERE provider IN ('Lucky Monaco', 'LuckyMonaco');
UPDATE bg_568win_game SET provider = 'Lucky Sports', provider_short = 'LKS' WHERE provider IN ('Lucky Sports', 'LuckySports');
UPDATE bg_568win_game SET provider = 'Manna Play', provider_short = 'MNP' WHERE provider IN ('Manna Play');
UPDATE bg_568win_game SET provider = 'Mascot Gaming', provider_short = 'MAS' WHERE provider IN ('Mascot Gaming');
UPDATE bg_568win_game SET provider = 'Microgaming', provider_short = 'MG' WHERE provider IN ('MicroGaming', 'Microgaming');
UPDATE bg_568win_game SET provider = 'MikiWorld', provider_short = 'MIKI' WHERE provider IN ('MikiWorld', 'MikiWorldLiveCasino');
UPDATE bg_568win_game SET provider = 'Mobilots', provider_short = 'MBL' WHERE provider IN ('Mobilots');
UPDATE bg_568win_game SET provider = 'MPoker', provider_short = 'MPK' WHERE provider IN ('MPoker');
UPDATE bg_568win_game SET provider = 'MT', provider_short = 'MT' WHERE provider IN ('MT', 'mt');
UPDATE bg_568win_game SET provider = 'Naga Games', provider_short = 'NAGA' WHERE provider IN ('Naga Games', 'NagaGames');
UPDATE bg_568win_game SET provider = 'NetEnt', provider_short = 'NE' WHERE provider IN ('NetEnt', 'Netent', 'NetentExtended');
UPDATE bg_568win_game SET provider = 'NetGame', provider_short = 'NG' WHERE provider IN ('NetGame');
UPDATE bg_568win_game SET provider = 'Nextspin', provider_short = 'NXS' WHERE provider IN ('Nextspin');
UPDATE bg_568win_game SET provider = 'Nolimit City', provider_short = 'NLC' WHERE provider IN ('NoLimitCity', 'Nolimit City');
UPDATE bg_568win_game SET provider = 'Nownow Gaming', provider_short = 'NN' WHERE provider IN ('Nownow Gaming');
UPDATE bg_568win_game SET provider = 'OG Live', provider_short = 'OG' WHERE provider IN ('OG Live', 'OGLive');
UPDATE bg_568win_game SET provider = 'Onlyplay', provider_short = 'OPL' WHERE provider IN ('Onlyplay');
UPDATE bg_568win_game SET provider = 'Panda Sports', provider_short = 'PDS' WHERE provider IN ('Panda Sports', 'PandaSports');
UPDATE bg_568win_game SET provider = 'Pegasus', provider_short = 'PEG' WHERE provider IN ('Pegasus', 'PegasusSlot');
UPDATE bg_568win_game SET provider = 'Peter & Sons', provider_short = 'PNS' WHERE provider IN ('Peter & Sons');
UPDATE bg_568win_game SET provider = 'PG Soft', provider_short = 'PG' WHERE provider IN ('PG Soft', 'PGSoft');
UPDATE bg_568win_game SET provider = 'Phoenix7', provider_short = 'PH7' WHERE provider IN ('Phoenix7');
UPDATE bg_568win_game SET provider = 'Platipus', provider_short = 'PLA' WHERE provider IN ('Platipus', 'Platipus Gaming');
UPDATE bg_568win_game SET provider = 'PlayAce', provider_short = 'PACE' WHERE provider IN ('PlayAce');
UPDATE bg_568win_game SET provider = 'Play''n GO', provider_short = 'PNG' WHERE provider IN ('Play''n GO');
UPDATE bg_568win_game SET provider = 'PlayStar', provider_short = 'PS' WHERE provider IN ('PlayStar');
UPDATE bg_568win_game SET provider = 'Playtech', provider_short = 'PT' WHERE provider IN ('PlayTech', 'Playtech', 'Playtech Casino');
UPDATE bg_568win_game SET provider = 'PoggiPlay', provider_short = 'POGGI' WHERE provider IN ('PoggiPlay');
UPDATE bg_568win_game SET provider = 'Popiplay', provider_short = 'POPI' WHERE provider IN ('Popiplay', 'Popiplay Gaming');
UPDATE bg_568win_game SET provider = 'Pragmatic Play', provider_short = 'PP' WHERE provider IN ('Pragmatic Play', 'Pragmatic Play Casino', 'PragmaticPlay', 'PragmaticPlayCasino');
UPDATE bg_568win_game SET provider = 'Predix', provider_short = 'PDX' WHERE provider IN ('Predix');
UPDATE bg_568win_game SET provider = 'Prospect Gaming', provider_short = 'PRO' WHERE provider IN ('Prospect Gaming');
UPDATE bg_568win_game SET provider = 'Qora', provider_short = 'QORA' WHERE provider IN ('Qora');
UPDATE bg_568win_game SET provider = 'Quickspin', provider_short = 'QS' WHERE provider IN ('Quickspin');
UPDATE bg_568win_game SET provider = 'Ready Play', provider_short = 'RDY' WHERE provider IN ('Ready Play');
UPDATE bg_568win_game SET provider = 'Red Rake', provider_short = 'RR' WHERE provider IN ('Red Rake', 'RedRake');
UPDATE bg_568win_game SET provider = 'Red Tiger', provider_short = 'RT' WHERE provider IN ('Red Tiger');
UPDATE bg_568win_game SET provider = 'ReelPlay', provider_short = 'RPL' WHERE provider IN ('ReelPlay');
UPDATE bg_568win_game SET provider = 'Relax Gaming', provider_short = 'RELAX' WHERE provider IN ('Relax Gaming', 'RelaxGaming');
UPDATE bg_568win_game SET provider = 'RevDev', provider_short = 'REV' WHERE provider IN ('RevDev');
UPDATE bg_568win_game SET provider = 'Revolver Gaming', provider_short = 'RVG' WHERE provider IN ('Revolver Gaming');
UPDATE bg_568win_game SET provider = 'Rich88', provider_short = 'R88' WHERE provider IN ('Rich88');
UPDATE bg_568win_game SET provider = 'Rival Powered', provider_short = 'RIV' WHERE provider IN ('Rival Powered');
UPDATE bg_568win_game SET provider = 'Rogue', provider_short = 'ROG' WHERE provider IN ('Rogue');
UPDATE bg_568win_game SET provider = 'Royal Slot Gaming', provider_short = 'RSG' WHERE provider IN ('Royal Slot Gaming', 'RoyalSlotGaming');
UPDATE bg_568win_game SET provider = 'RTG Slots', provider_short = 'RTG' WHERE provider IN ('RTG Slots');
UPDATE bg_568win_game SET provider = 'RubyPlay', provider_short = 'RUBY' WHERE provider IN ('RubyPlay', 'Rubyplay');
UPDATE bg_568win_game SET provider = 'Saba Sports', provider_short = 'SABA' WHERE provider IN ('Saba Sports');
UPDATE bg_568win_game SET provider = 'SA Gaming', provider_short = 'SA' WHERE provider IN ('SA Gaming', 'SaGaming');
UPDATE bg_568win_game SET provider = 'SBO Slot', provider_short = 'SBO' WHERE provider IN ('SBO Slot', 'SBOSlot');
UPDATE bg_568win_game SET provider = 'Sexy Gaming', provider_short = 'SEXY' WHERE provider IN ('Sexy Gaming', 'SexyGaming');
UPDATE bg_568win_game SET provider = 'Skywind', provider_short = 'SW' WHERE provider IN ('Skywind', 'Skywind Casino');
UPDATE bg_568win_game SET provider = 'Speedy Tomatoes', provider_short = 'SPT' WHERE provider IN ('Speedy Tomatoes');
UPDATE bg_568win_game SET provider = 'SPlus', provider_short = 'SPL' WHERE provider IN ('SPlus');
UPDATE bg_568win_game SET provider = 'Spribe', provider_short = 'SPRIBE' WHERE provider IN ('Spribe');
UPDATE bg_568win_game SET provider = 'TC Gaming', provider_short = 'TCG' WHERE provider IN ('TC Gaming', 'TCGaming');
UPDATE bg_568win_game SET provider = 'Thunderkick', provider_short = 'TK' WHERE provider IN ('Thunderkick');
UPDATE bg_568win_game SET provider = 'Tom Horn', provider_short = 'TH' WHERE provider IN ('Tom Horn', 'TomHorn');
UPDATE bg_568win_game SET provider = 'Triple PG', provider_short = 'TPG' WHERE provider IN ('Triple PG');
UPDATE bg_568win_game SET provider = 'Turbo Games', provider_short = 'TURBO' WHERE provider IN ('Turbo Games');
UPDATE bg_568win_game SET provider = 'Upgames', provider_short = 'UPG' WHERE provider IN ('Upgames');
UPDATE bg_568win_game SET provider = 'VA Gaming', provider_short = 'VA' WHERE provider IN ('VA Gaming', 'VAGaming');
UPDATE bg_568win_game SET provider = 'VGaming', provider_short = 'VG' WHERE provider IN ('VGaming', 'Vgaming');
UPDATE bg_568win_game SET provider = 'Via Casino', provider_short = 'VIA' WHERE provider IN ('Via Casino', 'ViaCasino');
UPDATE bg_568win_game SET provider = 'VoltEnt', provider_short = 'VOLT' WHERE provider IN ('VoltEnt');
UPDATE bg_568win_game SET provider = 'WanMei', provider_short = 'WME' WHERE provider IN ('WanMei');
UPDATE bg_568win_game SET provider = 'WCasino', provider_short = 'WCA' WHERE provider IN ('WCasino');
UPDATE bg_568win_game SET provider = 'WorldMatch', provider_short = 'WM' WHERE provider IN ('WorldMatch');
UPDATE bg_568win_game SET provider = 'WS168', provider_short = 'WS168' WHERE provider IN ('WS168', 'WS168Cockfighting');
UPDATE bg_568win_game SET provider = 'YeeBet', provider_short = 'YEE' WHERE provider IN ('YeeBet');
UPDATE bg_568win_game SET provider = 'Yggdrasil', provider_short = 'YGG' WHERE provider IN ('Yggdrasil');
UPDATE bg_568win_game SET provider = 'YGR', provider_short = 'YGR' WHERE provider IN ('YGR');
