-- 印尼市场客服 FAQ 与处理准则。内容来自现有客服咨询分类统计的归纳，不包含用户隐私或原始对话。
INSERT INTO `cs_faq` (`category`, `question`, `answer`, `lang`, `sort_order`) VALUES
('deposit', 'Bagaimana cara melakukan deposit?', 'Buka Dompet > Deposit, pilih IDR dan metode pembayaran yang tersedia, masukkan jumlah, lalu ikuti petunjuk pembayaran. Pastikan jumlah dan rekening tujuan sesuai dengan pesanan.', 'id', 10),
('deposit', 'Deposit saya belum masuk', 'Mohon kirim nomor pesanan deposit dan waktu pembayaran. Jangan kirim kata sandi atau OTP. Kami akan memeriksa status lokal dan referensi penyedia pembayaran. Pesanan yang tertunda lebih dari 30 menit akan diteruskan untuk pemeriksaan.', 'id', 20),
('deposit', 'Mengapa deposit saya gagal?', 'Periksa batas minimum/maksimum, saldo rekening, serta masa berlaku pesanan. Jangan membayar ulang pesanan yang sudah kedaluwarsa; buat pesanan baru atau hubungi layanan pelanggan dengan nomor pesanan.', 'id', 30),
('withdraw', 'Bagaimana cara menarik dana?', 'Selesaikan verifikasi identitas, buka Dompet > Withdraw, pilih IDR, isi rekening tujuan dan jumlah, lalu kirim permintaan. Nama pemilik rekening harus sesuai dengan data verifikasi.', 'id', 10),
('withdraw', 'Penarikan saya masih diproses', 'Mohon kirim nomor pesanan penarikan. Kami akan memeriksa status peninjauan dan pembayaran. Waktu proses dapat dipengaruhi pemeriksaan keamanan dan bank; kami tidak akan menjanjikan waktu selesai sebelum status terverifikasi.', 'id', 20),
('withdraw', 'Penarikan gagal tetapi saldo belum kembali', 'Mohon kirim nomor pesanan. Sistem hanya mengembalikan saldo satu kali setelah status gagal dikonfirmasi. Jika belum kembali, kami akan meneruskan pesanan untuk rekonsiliasi.', 'id', 30),
('account', 'Bagaimana memasukkan nomor Indonesia?', 'Gunakan kode negara +62. Nomor yang diawali 08 dapat dimasukkan sebagai 8xxxxxxxxxx setelah memilih Indonesia, atau dalam format internasional +628xxxxxxxxxx.', 'id', 10),
('account', 'Saya tidak bisa masuk ke akun', 'Pastikan metode login dan nomor/akun yang digunakan sama dengan saat mendaftar. Jangan berikan OTP atau kata sandi kepada siapa pun. Jika masih gagal, kirim tangkapan layar pesan kesalahan tanpa informasi sensitif.', 'id', 20),
('kyc', 'Dokumen apa yang dapat digunakan untuk KYC Indonesia?', 'Gunakan dokumen Indonesia yang masih berlaku, seperti KTP atau SIM sesuai pilihan yang tersedia. Foto harus jelas, tidak terpotong, dan data harus sama dengan pemilik akun.', 'id', 10),
('kyc', 'Mengapa verifikasi KYC saya ditolak?', 'Penyebab umum adalah foto buram, pantulan cahaya, dokumen terpotong, dokumen kedaluwarsa, atau data tidak cocok. Periksa alasan penolakan, lalu unggah ulang foto asli yang jelas.', 'id', 20),
('game', 'Game berhenti di layar loading', 'Periksa koneksi, tutup lalu buka kembali game, dan coba jaringan lain. Jika tetap terjadi, kirim nama game, waktu kejadian, dan tangkapan layar agar putaran dapat diperiksa.', 'id', 10),
('bonus', 'Bagaimana bonus dan rebate dihitung?', 'Buka halaman Bonuses, Tasks, Rebate, atau VIP untuk melihat syarat IDR, periode, dan progres. Setiap program memiliki ketentuan taruhan dan waktu klaim sendiri; nilai yang berlaku adalah yang ditampilkan pada halaman program.', 'id', 10),
('support_policy', 'Pedoman penanganan masalah pembayaran', 'Konfirmasi pengguna dan mata uang terlebih dahulu. Minta nomor pesanan, bukan kata sandi atau OTP. Periksa status lokal, referensi penyedia, jumlah, dan waktu. Teruskan untuk pemeriksaan jika tertunda lebih dari 30 menit, jumlah tidak cocok, callback tidak normal, atau pengembalian dana belum selesai.', 'id', 10),
('support_policy', 'Pedoman keamanan dan privasi', 'Jangan pernah meminta kata sandi, OTP, private key, nomor kartu lengkap, atau data rahasia lain. Kumpulkan data minimum yang diperlukan, samarkan informasi sensitif dalam tangkapan layar, dan jangan menyalin data pengguna ke catatan yang tidak diperlukan.', 'id', 20),
('support_policy', 'Pedoman kualitas jawaban', 'Jawab dengan bahasa pengguna, sebutkan mata uang secara jelas, jangan membuat janji yang belum terverifikasi, dan selalu berikan langkah berikutnya yang konkret. Jika diteruskan ke tim lain, jelaskan data yang sudah diperiksa dan alasan eskalasi.', 'id', 30);
