-- 根据 2026-07-22 至 2026-09-26 客服会话的匿名主题统计补充高频问答。
-- 仅新增知识，不包含客户原始消息或个人信息。
INSERT INTO `cs_faq` (`category`, `question`, `answer`, `lang`, `sort_order`) VALUES
('withdraw', 'My withdrawal failed or was rejected. What should I do?', 'Open Wallet and check the latest withdrawal status and rejection reason. Correct the stated issue before submitting again. A failed order should return the held amount once; if the balance is not restored after the status becomes failed, contact support with the withdrawal order ID. Never share your password or OTP.', 'en', 40),
('withdraw', 'Why can I not submit another withdrawal while one is pending?', 'Only one withdrawal can be processed at a time. Wait for the pending order to complete or fail before submitting another request. If its status does not change within the processing time shown on the page, contact support with the order ID.', 'en', 50),
('withdraw', 'Why does my withdrawal amount look different?', 'Check the order currency, requested amount, status, and any fee or gas fee shown on the withdrawal page. If these do not explain the difference, contact support with the order ID, expected amount, and actual amount; do not send a password or OTP.', 'en', 60),
('kyc', 'What are the requirements for uploading an ID?', 'Use a valid supported government ID. Upload a clear original photo with all corners visible, no glare or blur, and details that match the account holder. Check the rejection reason before uploading again.', 'en', 30),
('kyc', 'How can I pass face verification?', 'Use good lighting, keep your face centered and clearly visible, and follow each liveness instruction on screen. If it still fails, reopen KYC Setting, check your connection, and retry with a clear camera image.', 'en', 40),
('kyc', 'What should I do if phone or OTP verification fails?', 'Confirm the country code and phone number, check your signal and SMS inbox, then wait for the resend timer before requesting another code. Use only the newest OTP and never share it with anyone. If attempts are temporarily limited, wait and try again later.', 'en', 50),
('support', 'How do I talk to a human agent and follow up on my ticket?', 'Choose Talk to a human agent in Support. If an agent is online, wait in the current chat. If no agent is online, the issue is saved as a ticket; open My Tickets later to read the reply or add more information.', 'en', 10),
('withdraw', 'मेरी निकासी विफल या अस्वीकृत हो गई। मुझे क्या करना चाहिए?', 'वॉलेट खोलकर नवीनतम निकासी की स्थिति और अस्वीकृति का कारण देखें। दोबारा अनुरोध करने से पहले बताई गई समस्या ठीक करें। ऑर्डर विफल होने पर रोकी गई राशि एक बार वापस होनी चाहिए; स्थिति विफल होने के बाद भी बैलेंस वापस न आए तो निकासी ऑर्डर आईडी के साथ सहायता से संपर्क करें। पासवर्ड या OTP कभी साझा न करें।', 'hi', 40),
('withdraw', 'एक निकासी लंबित होने पर मैं दूसरी निकासी क्यों नहीं कर सकता?', 'एक समय में केवल एक निकासी प्रोसेस की जा सकती है। नया अनुरोध भेजने से पहले लंबित ऑर्डर के पूरा या विफल होने की प्रतीक्षा करें। पेज पर दिखाए गए प्रोसेसिंग समय में स्थिति न बदले तो ऑर्डर आईडी के साथ सहायता से संपर्क करें।', 'hi', 50),
('withdraw', 'मेरी निकासी राशि अलग क्यों दिख रही है?', 'ऑर्डर की मुद्रा, अनुरोधित राशि, स्थिति और निकासी पेज पर दिखाई गई फीस या गैस फीस जाँचें। अंतर का कारण न मिले तो ऑर्डर आईडी, अपेक्षित राशि और वास्तविक राशि के साथ सहायता से संपर्क करें; पासवर्ड या OTP न भेजें।', 'hi', 60),
('kyc', 'पहचान पत्र अपलोड करने की क्या आवश्यकताएँ हैं?', 'मान्य और समर्थित सरकारी पहचान पत्र उपयोग करें। साफ मूल फोटो अपलोड करें जिसमें सभी कोने दिखें, चमक या धुंधलापन न हो और जानकारी खाताधारक से मेल खाए। दोबारा अपलोड करने से पहले अस्वीकृति का कारण देखें।', 'hi', 30),
('kyc', 'चेहरा सत्यापन कैसे पूरा करूँ?', 'अच्छी रोशनी रखें, चेहरा बीच में और साफ दिखाई दे, और स्क्रीन पर दिए गए हर लाइवनेस निर्देश का पालन करें। फिर भी विफल हो तो KYC सेटिंग दोबारा खोलें, नेटवर्क जाँचें और साफ कैमरा तस्वीर के साथ फिर प्रयास करें।', 'hi', 40),
('kyc', 'फोन या OTP सत्यापन विफल हो तो क्या करूँ?', 'देश कोड और फोन नंबर की पुष्टि करें, नेटवर्क सिग्नल और SMS इनबॉक्स जाँचें, फिर नया कोड माँगने से पहले रीसेन्ड टाइमर पूरा होने दें। केवल सबसे नया OTP उपयोग करें और इसे किसी से साझा न करें। प्रयास अस्थायी रूप से सीमित हों तो प्रतीक्षा करके फिर कोशिश करें।', 'hi', 50),
('support', 'मानव एजेंट से कैसे बात करूँ और टिकट कैसे देखूँ?', 'सहायता में मानव एजेंट से बात करें चुनें। एजेंट ऑनलाइन हो तो इसी चैट में प्रतीक्षा करें। कोई एजेंट ऑनलाइन न हो तो समस्या टिकट के रूप में सेव होगी; जवाब पढ़ने या अधिक जानकारी जोड़ने के लिए बाद में मेरे टिकट खोलें।', 'hi', 10);
